# Generated by Django 4.0.3 on 2022-03-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
    ]
