# Generated by Django 4.0.3 on 2022-03-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llearn', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='name',
        ),
    ]
